server:
  port: 8085

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: userservice
              uri: lb://userservice
              predicates:
                - Path=/userservice/**
            - id: hotelservice
              uri: lb://hotelservice
              predicates:
                - Path=/hotelservice/**
            - id: ratingservice
              uri: lb://ratingservice
              predicates:
                - Path=/ratingservice/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka

